In [2]:
import sys
import numpy as np

In [3]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [20]:
a = np.array([5,3,2,1,1])
print(a)


[5 3 2 1 1]


In [10]:
b = np.array(([3,4,2],[2,2,2]))
print(b)

[[3 4 2]
 [2 2 2]]


In [16]:
print(b[:2,:3])

[[3 4 2]
 [2 2 2]]


In [18]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

In [25]:
print(b.shape)
     

(2, 3)


In [26]:
print(b.size)

6


In [27]:
print(b.dtype)


int64


In [28]:
print(b[0,1])


4


In [29]:
print(b[0,0])

3


In [30]:
print(b[1,0])


2


In [31]:
print(b[b>1])




[3 4 2 2 2 2]


In [32]:
print(b+1)


[[4 5 3]
 [3 3 3]]


In [ ]:
print(b.sum(a